from pydantic import BaseModel
from typing import Optional


# ── Final Response Schema ─────────────────────────────────────────────────────

class FinalResponse(BaseModel):
    """
    Complete validated response returned by the pipeline and API.
    Includes latency breakdown for performance monitoring.

    Why latency fields:
    Shows performance awareness — interviewers care about this.
    Tracks retrieval vs LLM time separately so we know bottlenecks.
    """
    intent: str
    entities: dict[str, str]
    similarity_score: float
    is_clear: bool
    retrieval_time_ms: float
    llm_time_ms: float
    total_time_ms: float
    retrieved_examples: list[str]
    message: str | None = None


# ── Constants ─────────────────────────────────────────────────────────────────

VALID_INTENTS = [
    "book_flight",
    "order_food",
    "check_weather",
    "cancel_booking",
    "track_order",
    "set_reminder",
    "play_music",
    "out_of_scope"
]

# Why 0.45:
# Tested against 30 diverse queries in Phase 2.
# Below 0.45 means the query is genuinely ambiguous or out of domain.
# Uses FAISS cosine similarity — mathematically meaningful.
# NOT LLM self-reported confidence which is invented.
SIMILARITY_THRESHOLD = 0.45


# ── Validator ─────────────────────────────────────────────────────────────────

class ResponseValidator:
    """
    Validates LLM output before it reaches the user.

    Key design decision:
    Uses FAISS similarity_score for the clarity threshold check.
    Does NOT use LLM self-reported confidence — that number is
    generated by the model and has no statistical meaning.
    FAISS cosine similarity is a real mathematical distance measure.
    """

    def __init__(self, valid_intents: list[str] = VALID_INTENTS):
        self.valid_intents = valid_intents

    def validate(self,
                 intent: str,
                 entities: dict,
                 similarity_score: float,
                 retrieved_examples: list[str],
                 retrieval_time_ms: float,
                 llm_time_ms: float,
                 total_time_ms: float) -> FinalResponse:
        """
        Validate LLM output and build final response.

        Args:
            intent: Intent string returned by LLM
            entities: Entities dict returned by LLM
            similarity_score: FAISS cosine similarity of top retrieved example
            retrieved_examples: List of example texts shown to LLM
            retrieval_time_ms: Time taken for FAISS search
            llm_time_ms: Time taken for LLM inference
            total_time_ms: Total pipeline time

        Returns:
            FinalResponse — always returns a valid object, never crashes
        """

        # Step 1 — Check clarity using FAISS similarity
        # This is the real confidence signal, not LLM confidence
        is_clear = similarity_score >= SIMILARITY_THRESHOLD

        if not is_clear:
            return FinalResponse(
                intent="unclear",
                entities={},
                similarity_score=similarity_score,
                is_clear=False,
                retrieval_time_ms=retrieval_time_ms,
                llm_time_ms=llm_time_ms,
                total_time_ms=total_time_ms,
                retrieved_examples=retrieved_examples,
                message="Could you please rephrase that? I am not sure what you mean."
            )

        # Step 2 — Validate intent exists in our defined schema
        # LLM might hallucinate an intent name not in our list
        validated_intent = intent
        if validated_intent not in self.valid_intents:
            validated_intent = "out_of_scope"

        # Step 3 — Build clean final response
        return FinalResponse(
            intent=validated_intent,
            entities=entities,
            similarity_score=similarity_score,
            is_clear=True,
            retrieval_time_ms=retrieval_time_ms,
            llm_time_ms=llm_time_ms,
            total_time_ms=total_time_ms,
            retrieved_examples=retrieved_examples,
            message=None
        )


# ── Quick Test ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Testing ResponseValidator...\n")

    validator = ResponseValidator()

    # Test 1 — Valid high similarity response
    r1 = validator.validate(
        intent="book_flight",
        entities={"location": "Delhi", "date": "tomorrow"},
        similarity_score=0.87,
        retrieved_examples=["Book a flight to Delhi"],
        retrieval_time_ms=12.5,
        llm_time_ms=800.0,
        total_time_ms=815.0
    )
    print("Test 1 — Valid response:")
    print(f"  Intent:   {r1.intent}")
    print(f"  Entities: {r1.entities}")
    print(f"  Clear:    {r1.is_clear}")
    assert r1.intent == "book_flight"
    assert r1.is_clear == True
    print("  ✅ Passed\n")

    # Test 2 — Unknown intent mapped to out_of_scope
    r2 = validator.validate(
        intent="unknown_intent_xyz",
        entities={},
        similarity_score=0.6,
        retrieved_examples=["some example"],
        retrieval_time_ms=10.0,
        llm_time_ms=700.0,
        total_time_ms=710.0
    )
    print("Test 2 — Unknown intent:")
    print(f"  Intent: {r2.intent}")
    assert r2.intent == "out_of_scope"
    print("  ✅ Passed\n")

    # Test 3 — Low similarity triggers unclear
    # Note: LLM says confidence 0.9 but FAISS similarity is 0.30
    # We trust FAISS, not LLM — so result is unclear
    r3 = validator.validate(
        intent="book_flight",
        entities={},
        similarity_score=0.30,
        retrieved_examples=["some example"],
        retrieval_time_ms=10.0,
        llm_time_ms=700.0,
        total_time_ms=710.0
    )
    print("Test 3 — Low similarity score:")
    print(f"  Intent:  {r3.intent}")
    print(f"  Clear:   {r3.is_clear}")
    print(f"  Message: {r3.message}")
    assert r3.intent == "unclear"
    assert r3.is_clear == False
    print("  ✅ Passed\n")

    # Test 4 — Exactly at threshold boundary
    r4 = validator.validate(
        intent="check_weather",
        entities={"location": "Mumbai"},
        similarity_score=0.45,
        retrieved_examples=["Weather in Mumbai"],
        retrieval_time_ms=11.0,
        llm_time_ms=750.0,
        total_time_ms=761.0
    )
    print("Test 4 — Exactly at threshold (0.45):")
    print(f"  Intent: {r4.intent}")
    print(f"  Clear:  {r4.is_clear}")
    assert r4.intent == "check_weather"
    assert r4.is_clear == True
    print("  ✅ Passed\n")

    # Test 5 — Empty entities handled correctly
    r5 = validator.validate(
        intent="play_music",
        entities={},
        similarity_score=0.72,
        retrieved_examples=["Play some music"],
        retrieval_time_ms=9.0,
        llm_time_ms=680.0,
        total_time_ms=689.0
    )
    print("Test 5 — Empty entities:")
    print(f"  Intent:   {r5.intent}")
    print(f"  Entities: {r5.entities}")
    assert r5.intent == "play_music"
    assert r5.entities == {}
    print("  ✅ Passed\n")

    print("=" * 40)
    print("✅ All 5 validator tests passed")
    print(f"✅ Threshold: {SIMILARITY_THRESHOLD}")
    print(f"✅ Valid intents: {len(VALID_INTENTS)}")